// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VagaSimplesDTO vaga simples d t o
//
// swagger:model VagaSimplesDTO
type VagaSimplesDTO struct {

	// descricao
	Descricao string `json:"Descricao,omitempty"`

	// nome
	Nome string `json:"Nome,omitempty"`

	// quantidade
	Quantidade string `json:"Quantidade,omitempty"`

	// salario
	Salario string `json:"Salario,omitempty"`

	// tipo
	Tipo string `json:"Tipo,omitempty"`
}

// Validate validates this vaga simples d t o
func (m *VagaSimplesDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VagaSimplesDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VagaSimplesDTO) UnmarshalBinary(b []byte) error {
	var res VagaSimplesDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
